# Generated by Django 4.1 on 2022-08-22 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_night_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='GameDetail',
        ),
        migrations.RemoveField(
            model_name='event',
            name='max_participants',
        ),
        migrations.RemoveField(
            model_name='eventuser',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventuser',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='group',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='grouplist',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='grouplist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='grouprequest',
            name='is_active',
        ),
        migrations.AddField(
            model_name='event',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=8, null=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='event',
            name='max_attendees',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Maximum attendees'),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='code',
            field=models.CharField(default=None, max_length=8, unique=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default=None, max_length=32, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='grouplist',
            name='group',
            field=models.ManyToManyField(default=None, related_name='Listgroups', to='game_night_app.group'),
        ),
        migrations.AddField(
            model_name='grouplist',
            name='owner',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grouprequest',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Requestgroups', to='game_night_app.group'),
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Addresses', to='game_night_app.address'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(max_length=16, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='private',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Private game'),
        ),
        migrations.AlterField(
            model_name='eventgame',
            name='game',
            field=models.CharField(max_length=32, unique=True, verbose_name='Game'),
        ),
        migrations.AlterField(
            model_name='grouprequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Groupreceiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grouprequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Groupsender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='game_night_app.event'),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Eventreceiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Eventsender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='eventrequest',
            unique_together={('sender', 'receiver')},
        ),
    ]
