# Generated by Django 4.1 on 2022-08-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_night_app', '0002_eventrequest_delete_gamedetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplist',
            name='group',
            field=models.ManyToManyField( related_name='Listgroups', to='game_night_app.group'),
        ),
    ]
